- .gitignore
- README.md
- Vagrantfile
- braid/settings.py
Problem
======
As there is no easy way to reproduce twisted infa hosts on your system development and testing of new features is a PITA
A Vagrant VM could help in create a stating server to be used for dev and testing.
Changes
=======
This builds on top #76
I have fixed the provisioning of root account and updated the docs.
How to test
=========
Install vagrant and follow the README steps.
Check  that docs make sense.
Check that you can start the vagrant VM and run a fab command.
As a test you can run the `base.bootstrap` command.
> Add vagrant configuration to help with infrastructre development / testing

- README.md
- Vagrantfile
- braid/settings.py
Fixes #75.
This appears to work to run `base.bootstrap` and `t-names.install`. But I haven't checked the results thereof.
> [WIP] Add basic vagrant file.

- .gitmodules
- README.md
- services/t-names/README
- services/t-names/crontab
- services/t-names/fabfile.py
- services/t-names/start
- services/t-names/zones/crookedsapling.us
- services/t-names/zones/divmod.com
- services/t-names/zones/divmod.org
- services/t-names/zones/divunal.com
- services/t-names/zones/hosts.py
- services/t-names/zones/twistedmatrix.com
- services/t-names/zones/ynchrono.us
Scope
=====
We want to move t-names braid config from a submodule to a simple subfolder in braid.
Changes
=======
Removed submodule and copied files from https://github.com/twisted-infra/t-names.
Update fabfile.py to update files from submodule, rather than git repo
twisted-infra/t-names was updated to inform that code is not in braid.
No need to migrate issues or PRs.
How to test
=========
```
fab -i ~/.vagrant.d/insecure_private_key config.vagrant t-names.install
fab -i ~/.vagrant.d/insecure_private_key config.vagrant t-names.start
host twistedmatrix.com 172.16.255.140
fab -i ~/.vagrant.d/insecure_private_key config.vagrant t-names.stop
host twistedmatrix.com 172.16.255.140
```
> Move t-names submodule into a simple folder

- .gitmodules
- README.md
- services/kenaan/README
- services/kenaan/_http.py
- services/kenaan/alert
- services/kenaan/alert.py
- services/kenaan/commit
- services/kenaan/commit.py
- services/kenaan/commit_bot.py
- services/kenaan/commit_bot.tac
- services/kenaan/config.py
- services/kenaan/crontab
- services/kenaan/fabfile.py
- services/kenaan/message
- services/kenaan/message.py
- services/kenaan/private.py.sample
- services/kenaan/start
- services/kenaan/ticket
- services/kenaan/ticket.py
Scope
======
We want to move kenaan infra code to a subfolder of braid to make it easier to hack it.
Changes
=======
Removed the subfolder and copy the https://github.com/twisted-infra/kenaan files.
I have updated the fabfile.py to push udpates from local folder.
I have also updated the fabfile.py to also update the private (production/testing) data on each update. 
testing data is now installed when `installPrivateData` is False. so that we can use a single flag for production and staging... similar to what is done for the buildmaster 
I have updated twisted-infra/kenaan repo description and moved the issues to braid and closed old issues.
How to test
=========
I was able to run the install and start the bot but it fails to connect. Most probably due to bad private data and the lack of a …
> Move kenaan submodule into a normal folder

- .gitmodules
- README.md
- services/amptrac/README
- services/amptrac/crontab
- services/amptrac/fabfile.py
- services/amptrac/start
Scope
=====
To simplify infra developlment we want to move the amptrac config from a git submodule to a normal folder.
Changes
=======
Removed the submodule and copied files from https://github.com/twisted-infra/amptrac-config
Update fabfile to install from local folder.
amptrac server is still installed using pip from https://github.com/twisted-infra/amptrac-server
amptrac-config README is pretty thin and it does not describe how it is supposed to be integrated with t-web or trac... I think that something is missing from the documentation as I was not able to apply the fabfile on vagrant vm
How to test
=========
amptrac config is broken as when I try to install it on the vagrant VM I get this
```
Fatal error: sudo() received nonzero return code 1 while executing!
Requested: /usr/bin/psql …
```
> Move Amptrac submodule as a folder

- README.md
- Vagrantfile
- provisioning/playbook.yml
- provisioning/roles/requirements-debian/tasks/main.yml
- provisioning/roles/systemupdate/tasks/main.yml
This changes the local Vagrant box to be provisioned by ansible. Eventually, more Ansible will replace the 'bootstrap' stuff and will make it easier to get repeatable infrastructure.
To test, just install Ansible, run `vagrant up`, and see that the Ansible stuff happens and everything is okay. Then run `fab config.vagrant base.bootstrap` to run the base machine bootstrapping, and everything should work.
> Vagrant + ansible provisioning

- .gitmodules
We no longer use diffresource as we use GitHub code browser.
You will need to manually clean your .git/config file.
> Remove diffresource submodule.

- services/buildbot/README
- services/buildbot/master/twisted_factories.py
Scope
====
pyserial is supported on py2 and py3 on Linux/Unix
We have a few tests depending on pyserial.
install it as part of base deps
Changes
=======
move pyserial into BASE_DEPENDENCIES
cleanup buildbot/README . The code is no in braid so there is not much help to tell once again that this is braid.
How to test
==========
From this branch run
```
$ fab config.production buildbot.update
```
I have already applied the changes in production
> Install pyserial as base deps

- README.md
With https://github.com/twisted-infra/braid/pull/150 being merged, there are no longer git submodules that need to be updated.
> remove instructions to update git submodules

- services/buildbot/master/twisted_factories.py
#184 broke dependency installation on Windows, because cryptography lands up in the list twice. Since pyopenssl depends on cryptography, we don't actually need cryptography in the main list for now; this is a hack, but it seems the easiest way to fix this. (cryptography can go back in the main list once we're not pinning it to weird versions on different platforms)
> Silly hack to fix dependency installation.

- services/trac/external.py
- services/trac/fabfile.py
- services/trac/trac-env/conf/trac.ini
How you can test this:
- set up your vagrant vm like usual (base.bootstrap, t-web.install, trac.install, t-web.start, trac.start)
- make some fake tls keys (t-web.makeTestTLSKeys, t-web.installTLSKeys)
- set `172.16.255.140 twistedmatrix.com` in your hosts file
- go to https://github.com/settings/developers , register a new application, put the client ID in `services/trac/trac-env/conf/trac.ini` right at the bottom -- the one in there right now is the prod ID
- ssh in to the vagrant vm, `sudo su trac; mkdir ~/secrets; cat $THEIDSECRET > ~/secrets/secret.txt`
- go to https://twistedmatrix.com/trac/ , click on the 'github login' button... you should be logged in!
Works on my instance :D
> Use GitHub for login

- README.md
- provisioning/playbook.yml
- services/t-web/README
- services/trac/README.rst
- services/trac/fabfile.py
- services/trac/trac-env/templates/site.html
Scope
=====
This tries to clean the external links in a ticket page
```
(13.05.2016 08:20:30) The topic for #twisted-admin is: twisted infrastrucutre | https://github.com/twisted-infra
(10:17:17) adiroiban: hawkowl: hi. do we still need the 'patch' link in trac? I think that github link is enough :)
(10:17:34) adiroiban: and the 'log' link is broken...
(10:17:39) adiroiban: and not sure if we want it
(11:51:02) glyph: adiroiban: yup, kill 'em both
```
Changes
=======
See diff.
I have renamed the 'github' link to 'branch-diff' as I feel that the github link is not a good description.
As a drive by I tried to update the documentation based on my experience on trying to run trac in the VM.
As a drive-by I have updated the ansible rules as I got a warning that `become` is the new fancy term …
> Remove log and patch links from ticket page. Update github link name.

- services/buildbot/fabfile.py
- services/buildbot/master/master.cfg
- services/buildbot/master/private.py.sample
Scope
=====
This add support for reporting build result status for all builds done by Buildbot  for fixing #147
Changes
=======
I have configured GitHub status reporting in the buildbot configuration.
I have created a dedicated OAuth app in GitHub for Buildbot status
https://github.com/organizations/twisted/settings/applications/373261
I have set its logo to the Buildbot nut logo :) Feel free to suggest any other image
For testing, I got my own token... and before deploying in production I will update the private repo with the token generated for the dedicated OAuth app
How to test
=========
You can see it in action here
* For a PR  https://github.com/twisted/twisted/pull/212
* For a branch comparison https://github.com/twisted/twisted/compare/8494-codecov-config
Once this hit production …
> Send builder status to GitHub

- services/buildbot/README
- services/buildbot/fabfile.py
- services/buildbot/master/master.cfg
- services/buildbot/master/private.py.sample
- services/buildbot/master/txbuildbot/scheduler.py
- services/buildbot/master/txbuildbot/web.py
Scope
======
This add support for triggering builds when branches are pushed.
This tries to fix #202
Change
======
For now, the secret / payload authentication  is not enabled as I don't have write access to the private repo. The variables for supporting authentication are defined.
For now only the supported builds are auto-triggered for non-trunk branches. 
txbuildbot/scheduler.py was removed as it was only used for fileIsImportant and this  can be configured with a simple callable.
TwistedGitHubEventHandler was created only to prevent accidental hooks on PR.
If we want to enable building on PR, we should create a new issue in brain and test this scenario.
The production builders uses a secret token and it always asks for signed payloads.
For Vagrant VM the sample private files come …
> [#202] Trigger builds on push via GitHub webhooks

- services/buildbot/master/master.cfg
- services/buildbot/master/private.py.sample
Scope
=====
In this way it should be easier to allow people to access it for maintenance
I saw that we are using only about $700 of rax invoice.
The windows slave was quite busy sometimes so a second slave should help
Changes
=======
I have created the smallest win2012r2 windows vm on RAX
The private repo was already pushed.
I am documenting the steps required to have a windows slave here https://twistedmatrix.com/trac/wiki/ContinuousIntegration/Buildslaves#BuildslaveonWindows
For now the new slaves are in the unsuported category as I did not managed to start buildslave a a service. 
I can start it in debug mode... but when I use the Windows service tool, it fails to start
The builddir option is no longer used as I think that it is automatically created by buildslave based on the builder …
> Add Windows slave hosted by Rackspace

- services/trac/trac-env/conf/trac.ini
Fixes the issue where GitHub would get points in highscores
https://trac.edgewall.org/wiki/TracIni#git-section
@Hawkowl is awesome
> Disable use_committer_id

- services/buildbot/master/master.cfg
- services/buildbot/master/private.py.sample
- services/buildbot/master/twisted_factories.py
- services/buildbot/master/twisted_steps.py
This requires Twisted updates https://twistedmatrix.com/trac/ticket/8544 so that we have tox env for everything
This creates tox/venv builders for nomodules and bdist ... and windows builders 
After this merged, #220 should be easy to fix
windows builders are stuck at cleaning/recreating the venv
> Create tox / venv builder for all builders

- services/trac/fabfile.py
This should hopefully fix the broken captcha.
This pulls in at least https://trac.edgewall.org/changeset/14578 but just update to the latest version.
> Update trac's spam plugin.

- services/t-web/vhosts/twistedmatrix.com/447b8a411ca97c916307498bfa13edc5.txt
https://detectify.com - this is how they will validate that we own twistedmatrix.com (otherwise we won't be able to run their scanner against twistedmatrix.com).
> Add a file to twistedmatrix.com to be used by Detectify to validate ownership

- braid/venv.py
- services/t-web/fabfile.py
- services/t-web/twisted-web/ports
txacme will not create the certificates directory.  This introduces a
new fabric task to the t-web service, makeTxacmeCertificatesDirectory,
that should be run prior to activating the server.
See the first note here:
http://txacme.readthedocs.io/en/0.9.1/using.html
@glyph
> Use txacme.

- services/buildbot/master/master.cfg
@mithrandi pointed out that incremental fails to install because setuptools downloads requirements in a distribution's `setup_requires`, not `pip`.  That means we need a Python installation whose (`urllib.request`|`urllib2`)`.urlopen` can speak TLS 1.2 to PyPI.org.
I've installed Python 2.7.14, 3.5.3, and 3.6.5 under the buildbot user via `pyenv`; `pyenv` evidently downloads OpenSSL 1.0.2 and links `_ssl` against it on older macOS releases:
https://github.com/pyenv/pyenv/blob/b960f863ccf81e1311706b0976fde78e58141704/plugins/python-build/share/python-build/3.6.5#L2
https://github.com/pyenv/pyenv/blob/b960f863ccf81e1311706b0976fde78e58141704/plugins/python-build/bin/python-build#L1479-L1484
I did not use brew because other things have been installed in /usr/local/bin, and I want everything …
> Switch macOS builder to pyenv

- services/t-web/twisted-web/twisted-web
twisted.web.server.Request.getURLPath doesn't include query parameters
or Request.postpath, so it's the wrong thing to use.  Construct the
new URL manually instead.
> HTTPS redirect includes query parameters.

- services/trac/trac-env/conf/trac.ini
I hope that this fixed the invalid login URL.
I am not sure how to deploy this.
I hope someone will know how to push this in production.
> Add valid login URL.

- services/t-names/zones/twistedmatrix.com
This adds a docs.twistedmatrix.com which will redirect to the Read the docs service.
The plan is to use docs.twistedmatrix.com as the canonical domain for hosting the docs.
There will be a second PR to redirect https://twistedmatrix.com/documents/current/ to the new domain, but first we should have this pushed to PROD and make sure it works and later we can push the redirection.
> add readthedocs CNAME

- services/t-web/README.certbot
- services/t-web/fabfile.py
- services/t-web/t-web.service
- services/t-web/t-web.sh
- services/t-web/twisted-web/twisted-web
Per discussion on IRC, I hacked up t-web on the Azure VM to use certbot for certificate renewal. This required modifications to the ``twisted-web`` application so that it would serve ``http://twistedmatrix.com/.well-known/acme-challenge`` because txacme was wired to own that hierarchy. With that done I could follow the [certbot webroot instructions](https://certbot.eff.org/lets-encrypt/ubuntufocal-other). I copied the full script as deployed into this PR because there appear to have been other changes made to it.
I was a bit confused about the service was started and supervised (well, not supervised it seems?). I ended up replacing the init script run from cron with a systemd service, so here are the artifacts I generated as part of that. I didn't really attempt to update Braid properly. …
> Hacky twistedweb.com cert renewal

- services/t-web/README.certbot
- services/t-web/t-web.sh
Follow-up to #280 that actually works. Turns out I forgot to set up the symlinks I meant to, and also that symlinks wouldn't work anyway.
Glad I did some more testing... guess this is what happens with late-nine sysadmining. :grimacing:
> Deploy hook
